
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry uriEntry;

	private global::Gtk.Button connectButton;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button leftButton;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button upButton;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button zoominButton;

	private global::Gtk.Button zoomoutButton;

	private global::Gtk.Button downButton;

	private global::Gtk.Button rightButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.uriEntry = new global::Gtk.Entry();
		this.uriEntry.CanFocus = true;
		this.uriEntry.Name = "uriEntry";
		this.uriEntry.IsEditable = true;
		this.uriEntry.InvisibleChar = '●';
		this.vbox1.Add(this.uriEntry);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.uriEntry]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.connectButton = new global::Gtk.Button();
		this.connectButton.CanFocus = true;
		this.connectButton.Name = "connectButton";
		this.connectButton.UseUnderline = true;
		this.connectButton.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.vbox1.Add(this.connectButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.connectButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.leftButton = new global::Gtk.Button();
		this.leftButton.CanFocus = true;
		this.leftButton.Name = "leftButton";
		this.leftButton.UseUnderline = true;
		global::Gtk.Image w3 = new global::Gtk.Image();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-back", global::Gtk.IconSize.Button);
		this.leftButton.Image = w3;
		this.hbox1.Add(this.leftButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.leftButton]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.upButton = new global::Gtk.Button();
		this.upButton.CanFocus = true;
		this.upButton.Name = "upButton";
		this.upButton.UseUnderline = true;
		this.upButton.Label = global::Mono.Unix.Catalog.GetString("_");
		global::Gtk.Image w5 = new global::Gtk.Image();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-up", global::Gtk.IconSize.Button);
		this.upButton.Image = w5;
		this.vbox2.Add(this.upButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.upButton]));
		w6.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.zoominButton = new global::Gtk.Button();
		this.zoominButton.CanFocus = true;
		this.zoominButton.Name = "zoominButton";
		this.zoominButton.UseUnderline = true;
		global::Gtk.Image w7 = new global::Gtk.Image();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-zoom-in", global::Gtk.IconSize.Button);
		this.zoominButton.Image = w7;
		this.hbox3.Add(this.zoominButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.zoominButton]));
		w8.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.zoomoutButton = new global::Gtk.Button();
		this.zoomoutButton.CanFocus = true;
		this.zoomoutButton.Name = "zoomoutButton";
		this.zoomoutButton.UseUnderline = true;
		global::Gtk.Image w9 = new global::Gtk.Image();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-zoom-out", global::Gtk.IconSize.Button);
		this.zoomoutButton.Image = w9;
		this.hbox3.Add(this.zoomoutButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.zoomoutButton]));
		w10.Position = 1;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.downButton = new global::Gtk.Button();
		this.downButton.CanFocus = true;
		this.downButton.Name = "downButton";
		this.downButton.UseUnderline = true;
		global::Gtk.Image w12 = new global::Gtk.Image();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-down", global::Gtk.IconSize.Button);
		this.downButton.Image = w12;
		this.vbox2.Add(this.downButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.downButton]));
		w13.Position = 2;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w14.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.rightButton = new global::Gtk.Button();
		this.rightButton.CanFocus = true;
		this.rightButton.Name = "rightButton";
		this.rightButton.UseUnderline = true;
		global::Gtk.Image w15 = new global::Gtk.Image();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-forward", global::Gtk.IconSize.Button);
		this.rightButton.Image = w15;
		this.hbox1.Add(this.rightButton);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.rightButton]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.hbox1.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
